name: pulse
description: "MEWs project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7+1
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  web_socket_channel: ^3.0.2
  flutter_client_sse: ^2.0.3
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^3.1.1
  firebase_database: ^11.3.3 
  cloud_firestore: ^5.6.4
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  font_awesome_flutter: ^10.8.0
  csv: ^6.0.0
  http: ^1.3.0
  collection: ^1.19.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  open_file: ^3.5.10
  uuid: ^4.5.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_messaging: ^15.2.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lang/en-US.json
    - lang/th-TH.json
    - assets/
    - assets/images/
    - assets/images/flags/
    - assets/images/emojis/
    - assets/quotes/quotes.json 
  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Bold.otf
          weight: 700