default_platform(:android)

platform :android do
  desc "Build APK and upload to Firebase"

  lane :distribute_staging do
    sh("flutter build apk --release --build-number=#{ENV['GITHUB_RUN_NUMBER']}")

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "tuh-mews-tester",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "firebase-key.json"
    )
  end

  lane :distribute_production do
    sh("flutter build apk --release --build-number=#{ENV['GITHUB_RUN_NUMBER']}")

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_PROD"],
      groups: "all-users",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "firebase-key.json"
    )
  end
end