default_platform(:android)

platform :android do
  desc "Build APK and upload to Firebase"
  lane :distribute_staging do
    sh("flutter build apk --release --no-codesign")
    
    # 2. อัปโหลดไป Firebase
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID"],
      groups: "TUH MEWS Tester",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "firebase-key.json"
    )
  end
end